# Generated by Django 5.1.6 on 2025-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_icone_delete_subtitulo_alter_redesocial_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subtítulo',
                'verbose_name_plural': 'Subtítulos',
            },
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='icone',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Icone',
        ),
    ]
