# Generated by Django 5.1.6 on 2025-02-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subtitulo_alter_redesocial_icone_delete_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ícone',
                'verbose_name_plural': 'Ícones',
            },
        ),
        migrations.DeleteModel(
            name='Subtitulo',
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='icone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.icone'),
        ),
    ]
