# Generated by Django 5.1.6 on 2025-02-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_icone_delete_subtitulo_alter_redesocial_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redesocial',
            name='texto',
        ),
    ]
